apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-allow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-allow
  template:
    metadata:
      labels:
        app: testapp-allow
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          tcpSocket:
            host:
            port: 80

