apiVersion: constraints.gatekeeper.sh/v1beta1
kind: restrictname
metadata:
  name: restrictname
spec:
  #enforcementAction: warn # deny (default) https://open-policy-agent.github.io/gatekeeper/website/docs/violations
  #enforcementAction: deny
  match:
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    denyname: "test"
